version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      # NOTE і тут теж реквізити мали б заповнюватись на сервері, краще через .ENV файл
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PandaTeam
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
      TZ: Europe/Kiev
    volumes: 
      - ./db:/docker-entrypoint-initdb.d

  php-app:
    build: 
      context: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root